### ISSUE TITLE
LET ME CHANGE THE README

### ISSUE THREAD

**Issue by whippingdot** [VirraLang/virra#2]
😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡

**Comment by zplusfour** [comment]
+ let me join the repl please

**Comment by StringentDev** [comment]
@whippingdot @zplusfour members now have, by default, write permissions so try that. Git Push should now work due to this perm change i have applied.

@zplusfour no spamming ok? i got like 64 notifs from you in one day on that occasion.

**Comment by zplusfour** [comment]
ok im sorry
