### ISSUE TITLE
Haha

### ISSUE THREAD

**Issue by firefish111** [VirraLang/virra#7]
Haha yes

**Comment by JBYT27** [comment]
Haha yes 

> It will only become official if HahaYes 'Haha yes's this. xD

**Comment by StringentDev** [comment]
HahaYes

**Comment by firefish111** [comment]
yeah i dont think anybody remembers hahayes anymore not many people worked with him in hahachat
he was then exposed for plaigiarism aand then disappeared

**Comment by StringentDev** [comment]
@firefish111 @JBYT27  we have discussions for a reason guys. just so we dont clog this place up :D

**Comment by firefish111** [comment]
discussions? what's that?
